version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mini_etl_db
    environment:
      POSTGRES_USER: seojin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
